# Generated by Django 6.0.4 on 2026-04-18 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
