-- PostgreSQL schema and seed data

-- Customers
CREATE TABLE IF NOT EXISTS customers (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT,
  address TEXT,
  total NUMERIC(12,2) DEFAULT 0,
  username TEXT UNIQUE,
  password TEXT
);

-- Staff
CREATE TABLE IF NOT EXISTS staff (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT
);

-- Inventory
CREATE TABLE IF NOT EXISTS inventory (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  category TEXT NOT NULL,
  name TEXT NOT NULL,
  brand TEXT NOT NULL,
  price NUMERIC(12,2) NOT NULL,
  stock INTEGER NOT NULL,
  threshold INTEGER NOT NULL
);

-- Invoices
CREATE TABLE IF NOT EXISTS invoices (
  id TEXT PRIMARY KEY,
  date DATE NOT NULL,
  customer TEXT NOT NULL,
  phone TEXT,
  customer_id INTEGER,
  customer_username TEXT,
  subtotal NUMERIC(12,2) NOT NULL,
  tax NUMERIC(12,2) NOT NULL,
  discount NUMERIC(12,2) NOT NULL,
  total NUMERIC(12,2) NOT NULL,
  CONSTRAINT invoices_customer_fk FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL
);

-- Orders (notifications for admin/cashier)
CREATE TABLE IF NOT EXISTS orders (
  id TEXT PRIMARY KEY,
  invoice_id TEXT NOT NULL,
  date DATE NOT NULL,
  customer TEXT NOT NULL,
  total NUMERIC(12,2) NOT NULL,
  status TEXT NOT NULL DEFAULT 'open',
  source TEXT NOT NULL,
  finished_at DATE,
  CONSTRAINT orders_invoice_fk FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE
);

-- Invoice items
CREATE TABLE IF NOT EXISTS invoice_items (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  invoice_id TEXT NOT NULL,
  part TEXT NOT NULL,
  brand TEXT NOT NULL,
  price NUMERIC(12,2) NOT NULL,
  qty INTEGER NOT NULL,
  amount NUMERIC(12,2) NOT NULL,
  CONSTRAINT invoice_items_invoice_fk FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE
);

-- Payments (1:1 with invoices)
CREATE TABLE IF NOT EXISTS payments (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  invoice_id TEXT NOT NULL UNIQUE,
  method TEXT NOT NULL,
  paid NUMERIC(12,2) NOT NULL,
  balance NUMERIC(12,2) NOT NULL,
  status TEXT NOT NULL,
  txn_id TEXT,
  date DATE NOT NULL,
  CONSTRAINT payments_invoice_fk FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE
);

-- Settings
CREATE TABLE IF NOT EXISTS settings (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  business_name TEXT NOT NULL,
  gst TEXT,
  phone TEXT,
  email TEXT,
  footer TEXT
);

-- Seed data: Customers
INSERT INTO customers (id, name, phone, email, address, total, username, password) VALUES
  (1, 'Rahul Motors', '9876543210', 'rahul@gmail.com', 'Mumbai', 0, 'rahul', 'rahul123'),
  (2, 'Speed Garage', '9123456780', 'speed@gmail.com', 'Pune', 0, 'speed', 'speed123'),
  (3, 'Premium Auto', '9988776655', 'premium@gmail.com', 'Delhi', 0, 'premium', 'premium123'),
  (4, 'City Service', '9876123450', 'city@gmail.com', 'Bangalore', 0, 'city', 'city123'),
  (5, 'Metro Auto Works', '9822334455', 'metro@gmail.com', 'Hyderabad', 0, 'metro', 'metro123'),
  (6, 'Northside Motors', '9811122233', 'northside@gmail.com', 'Chennai', 0, 'north', 'north123');

-- Seed data: Staff
INSERT INTO staff (id, name, role, phone, email) VALUES
  (1, 'Amit Sharma', 'Manager', '9000011111', 'amit@gmail.com'),
  (2, 'Neha Verma', 'Sales', '9000022222', 'neha@gmail.com'),
  (3, 'Rohit Iyer', 'Cashier', '9000033333', 'rohit@gmail.com'),
  (4, 'Sara Khan', 'Inventory', '9000044444', 'sara@gmail.com');

-- Seed data: Inventory
INSERT INTO inventory (id, category, name, brand, price, stock, threshold) VALUES
  (1, 'Engine Parts', 'Piston', 'Bosch', 1200, 3, 5),
  (2, 'Engine Parts', 'Piston', 'TVS', 1050, 7, 5),
  (3, 'Brake System', 'Brake Pad', 'TVS', 800, 15, 5),
  (4, 'Brake System', 'Brake Pad', 'Brembo', 950, 4, 5),
  (5, 'Filters', 'Oil Filter', 'Honda', 350, 2, 5),
  (6, 'Electrical', 'Alternator', 'Bosch', 3500, 8, 3),
  (7, 'Tires', 'MRF Tire', 'MRF', 2500, 20, 5),
  (8, 'Engine Parts', 'Gasket', 'TVS', 450, 12, 5),
  (9, 'Suspension', 'Shock Absorber', 'Monroe', 2200, 6, 4),
  (10, 'Electrical', 'Battery', 'Exide', 5200, 5, 3),
  (11, 'Filters', 'Air Filter', 'Bosch', 500, 9, 5),
  (12, 'Engine Parts', 'Piston', 'Mahle', 1150, 6, 5),
  (13, 'Engine Parts', 'Piston', 'ACL', 1100, 8, 5),
  (14, 'Brake System', 'Brake Pad', 'Bosch', 880, 10, 5),
  (15, 'Brake System', 'Brake Pad', 'EBC', 920, 7, 5),
  (16, 'Filters', 'Oil Filter', 'Bosch', 380, 11, 5),
  (17, 'Filters', 'Oil Filter', 'MANN', 400, 9, 5),
  (18, 'Filters', 'Oil Filter', 'Fram', 360, 13, 5),
  (19, 'Electrical', 'Alternator', 'Denso', 3400, 6, 3),
  (20, 'Electrical', 'Alternator', 'Valeo', 3600, 5, 3),
  (21, 'Electrical', 'Alternator', 'Lucas', 3300, 7, 3),
  (22, 'Tires', 'MRF Tire', 'Michelin', 2800, 12, 5),
  (23, 'Tires', 'MRF Tire', 'Bridgestone', 2700, 10, 5),
  (24, 'Tires', 'MRF Tire', 'Apollo', 2400, 14, 5),
  (25, 'Engine Parts', 'Gasket', 'Victor Reinz', 480, 9, 5),
  (26, 'Engine Parts', 'Gasket', 'Fel-Pro', 520, 7, 5),
  (27, 'Engine Parts', 'Gasket', 'Ajusa', 470, 8, 5),
  (28, 'Suspension', 'Shock Absorber', 'KYB', 2300, 5, 4),
  (29, 'Suspension', 'Shock Absorber', 'Gabriel', 2100, 7, 4),
  (30, 'Suspension', 'Shock Absorber', 'Bilstein', 2600, 4, 4),
  (31, 'Electrical', 'Battery', 'Amaron', 5100, 6, 3),
  (32, 'Electrical', 'Battery', 'Bosch', 5400, 5, 3),
  (33, 'Electrical', 'Battery', 'Luminous', 4800, 8, 3),
  (34, 'Filters', 'Air Filter', 'MANN', 520, 10, 5),
  (35, 'Filters', 'Air Filter', 'Fram', 480, 12, 5),
  (36, 'Filters', 'Air Filter', 'Mahle', 510, 11, 5);

-- Seed data: Invoices
INSERT INTO invoices (id, date, customer, phone, customer_id, customer_username, subtotal, tax, discount, total) VALUES
  ('INV-1001', '2026-03-10', 'Rahul Motors', '9876543210', 1, 'rahul', 1900, 95, 0, 1995),
  ('INV-1002', '2026-03-12', 'Speed Garage', '9123456780', 2, 'speed', 1600, 80, 0, 1680);

-- Seed data: Invoice items
INSERT INTO invoice_items (invoice_id, part, brand, price, qty, amount) VALUES
  ('INV-1001', 'Piston', 'Bosch', 1200, 1, 1200),
  ('INV-1001', 'Oil Filter', 'Honda', 350, 2, 700),
  ('INV-1002', 'Brake Pad', 'TVS', 800, 2, 1600);

-- Seed data: Payments
INSERT INTO payments (invoice_id, method, paid, balance, status, txn_id, date) VALUES
  ('INV-1001', 'UPI', 1995, 0, 'Paid', 'UPI-123456789', '2026-03-10'),
  ('INV-1002', 'Cash', 800, 880, 'Partial', '', '2026-03-12');

-- Seed data: Settings
INSERT INTO settings (id, business_name, gst, phone, email, footer) VALUES
  (1, 'SpareBill Auto Parts', 'GSTIN123456', '9876543210', 'sparebill@example.com', 'Thank you for your business!');
